# Generated by Django 5.2.6 on 2025-10-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='progress',
        ),
        migrations.CreateModel(
            name='lessons_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Список занятий')),
                ('lessons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.lessons')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student')),
            ],
            options={
                'verbose_name': 'Список занятий',
                'verbose_name_plural': 'Списки занятий',
            },
        ),
    ]
