# Generated by Django 5.2.6 on 2025-10-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_enrollments_progress_lessons_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons_list',
            options={'verbose_name': 'Список пройденных занятий', 'verbose_name_plural': 'Списки пройденных занятий'},
        ),
        migrations.AlterField(
            model_name='lessons_list',
            name='enrollment_date',
            field=models.DateField(verbose_name='Список пройденных занятий'),
        ),
    ]
