# Generated by Django 5.2.7 on 2025-10-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_lessons_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lessons_list',
            name='enrollment_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
